/* ================================================================
   ERA-VIS AI — vmdMaster.js
   Master tetap 119 toko untuk Visual Merchandising Compliance.
   Sumber: "Draft Visual Merchandising Compliance.xlsx" (kolom SAP CODE + STORE NAME).
   Seluruh toko ini SELALU tampil di halaman VMD Compliance, terlepas
   dari apakah toko ikut alokasi campaign atau tidak.

   Untuk update daftar: ganti isi array di bawah (atau nanti bisa
   di-load dari sheet Master Toko di Settings).
   ================================================================ */
'use strict';

const VMD_MASTER_STORES = [
  { code: 'E396', name: 'ERAFONE ANDMORE RUKO ITC ROXY MAS' },
  { code: 'E096', name: 'ERAFONE 2 ITC ROXY MAS' },
  { code: 'E037', name: 'ERAFONE GAJAH MADA PLAZA' },
  { code: 'E216', name: 'ERAFONE SENAYAN PARK' },
  { code: 'E281', name: 'ERAFONE 3.0 SENAYAN CITY' },
  { code: 'E678', name: 'ERAFONE MULTIBRAND BENDUNGAN HILIR' },
  { code: 'E682', name: 'ERAFONE MB KH MANSYUR TANAH ABANG' },
  { code: 'E898', name: 'ERAFONE MB SAMANHUDI' },
  { code: 'F073', name: 'ERAFONE 2.5 AGORA MALL' },
  { code: 'F133', name: 'ERAFONE DOSS RATU PLAZA JAKARTA' },
  { code: 'E047', name: 'ERAFONE 1 ITC CEMPAKA MAS' },
  { code: 'E113', name: 'ERAFONE GRAND INDONESIA' },
  { code: 'E038', name: 'ERAFONE MAL ATRIUM SENEN (ERAFONE MILLENIUM MALL)' },
  { code: 'E137', name: 'ERAFONE GREEN PRAMUKA SQUARE' },
  { code: 'E408', name: 'ERAFONE FRANCHISE RUKO SUMUR BATU' },
  { code: 'E414', name: 'ERAFONE RUKO PERCETAKAN NEGARA' },
  { code: 'E420', name: 'ERAFONE RUKO CEMPAKA PUTIH' },
  { code: 'E663', name: 'ERAFONE RUKO GARUDA KEMAYORAN' },
  { code: 'E732', name: 'ERAFONE RUKO SABANG' },
  { code: 'M212', name: 'ERAFONE AND MORE RAWASARI' },
  { code: 'E027', name: 'ERAFONE DAAN MOGOT MALL' },
  { code: 'E215', name: 'ERAFONE GREEN SEDAYU MALL' },
  { code: 'M068', name: 'ERAFONE AND MORE KAMAL RAYA' },
  { code: 'E233', name: 'ERAFONE RUKO TAMAN SURYA JAKBA' },
  { code: 'E312', name: 'ERAFONE KRESEK KOSAMBI' },
  { code: 'E381', name: 'ERAFONE RUKO PETA BARAT JAKBAR' },
  { code: 'E453', name: 'ERAFONE RUKO DURI KOSAMBI' },
  { code: 'E960', name: 'ERAFONE MB MENCENG RAYA' },
  { code: 'E992', name: 'ERAFONE 2.5 KAPUK CENGKARENG' },
  { code: 'E875', name: 'ERAFONE MB POS PENGUMBEN' },
  { code: 'E413', name: 'ERAFONE RUKO GOLDEN GREEN KEDOYA' },
  { code: 'E465', name: 'ERAFONE RUKO KEBAYORAN LAMA' },
  { code: 'E923', name: 'ERAFONE MB JALAN PANJANG' },
  { code: 'E943', name: 'ERAFONE MB TAMAN RATU' },
  { code: 'E028', name: 'ERAFONE MAL PURI INDAH' },
  { code: 'E029', name: 'ERAFONE PX PAVILION ST MORITS' },
  { code: 'E322', name: 'ERAFONE RUKO MERUYA' },
  { code: 'E514', name: 'ERAFONE FRANCHISE RUKO MERUYA SELATAN' },
  { code: 'E679', name: 'ERAFONE MULTIBRAND JOGLO RAYA' },
  { code: 'E582', name: 'ERAFONE MB SRENGSENG' },
  { code: 'E942', name: 'ERAFONE KEMBANGAN UTARA' },
  { code: 'E616', name: 'ERAFONE MERUYA ILIR' },
  { code: 'M219', name: 'ERAFONE AND MORE PURI INDAH MALL' },
  { code: 'E172', name: 'ERAFONE RUKO KEBON JERUK BINUS' },
  { code: 'E593', name: 'ERAFONE MANGGA BESAR' },
  { code: 'E508', name: 'ERAFONE JEMBATAN LIMA' },
  { code: 'E164', name: 'ERAFONE MAL TAMAN ANGGREK' },
  { code: 'M091', name: 'MEGASTORE CENTRAL PARK 3.0' },
  { code: 'E158', name: 'ERAFONE MAL CIPUTRA JAKARTA' },
  { code: 'E991', name: 'ERAFONE 2.5 KEMANGGISAN UTAMA RAYA' },
  { code: 'E043', name: 'ERAFONE PLAZA BINTARO JAYA' },
  { code: 'E160', name: 'ERAFONE RUKO CEGER TANGERANG' },
  { code: 'M014', name: 'MEGASTORE BINTARO X-CHANGE' },
  { code: 'M027', name: 'ERAFONE AND MORE CIPUTAT' },
  { code: 'E685', name: 'ERAFONE MB PONDOK BETUNG' },
  { code: 'E321', name: 'ERAFONE RUKO SUDIMARA CIPUTAT' },
  { code: 'M104', name: 'MEGASTORE RUKO REMPOA CIPUTAT' },
  { code: 'E391', name: 'ERAFONE RUKO WR SUPRATMAN CIPUTAT' },
  { code: 'E612', name: 'ERAFONE RUKO JOMBANG TANGSEL' },
  { code: 'E704', name: 'ERAFONE RUKO DEWANTARA CIPUTAT' },
  { code: 'E620', name: 'ERAFONE 2.5 PAJAJARAN PAMULANG' },
  { code: 'E084', name: 'ERAFONE 1 SUPERMALL KARAWACI' },
  { code: 'M163', name: 'ERAFONE AND MORE SERPONG' },
  { code: 'E777', name: 'ERAFONE MB CIHUNI PAGEDANGAN (ERAFONE CIHUNI GADING SERPONG)' },
  { code: 'E873', name: 'ERAFONE MB LEGOK' },
  { code: 'E874', name: 'ERAFONE MULTIBRAND DASANA INDAH' },
  { code: 'E813', name: 'ERAFONE MULTIBRAND SERPONG GARDEN CISAUK' },
  { code: 'M019', name: 'MEGASTORE SUMMARECON MAL SERPONG' },
  { code: 'M013', name: 'MEGASTORE SUPERMAL KARAWACI' },
  { code: 'M222', name: 'ERAFONE AND MORE EASTVARA MALL' },
  { code: 'E221', name: 'ERAFONE MALL CITRARAYA TANGERANG' },
  { code: 'F058', name: 'ERAFONE 2.5 TELAGA BESTARI' },
  { code: 'M048', name: 'MEGASTORE RUKO CIKUPA' },
  { code: 'M167', name: 'ERAFONE AND MORE TELUK NAGA' },
  { code: 'E627', name: 'ERAFONE RUKO CISOKA' },
  { code: 'E253', name: 'ERAFONE RUKO CURUG TANGERANG' },
  { code: 'E787', name: 'ERAFONE MB TIGARAKSA' },
  { code: 'E848', name: 'ERAFONE PASAR KEMIS' },
  { code: 'E812', name: 'ERAFONE RUKO KUTABUMI' },
  { code: 'E201', name: 'ERAFONE RUKO KRESEK BALARAJA' },
  { code: 'E744', name: 'ERAFONE RUKO RAJEG TANGERANG' },
  { code: 'F066', name: 'ERAFONE 2.5 SEPATAN' },
  { code: 'F079', name: 'ERAFONE 2.5 GRAND BATAVIA' },
  { code: 'F003', name: 'ERAFONE CILEDUG 2.5 RAYA' },
  { code: 'E231', name: 'ERAFONE RUKO COKROAMINOTO CILEDUG' },
  { code: 'E646', name: 'ERAFONE BATU CEPER' },
  { code: 'M021', name: 'MEGASTORE RUKO CILEDUG' },
  { code: 'E290', name: 'ERAFONE FRANCHISE RUKO PORIS' },
  { code: 'M093', name: 'MEGASTORE RUKO CIPONDOH TANGERANG' },
  { code: 'E150', name: 'ERAFONE CILEGON CENTER MALL' },
  { code: 'E081', name: 'ERAFONE MALL OF SERANG' },
  { code: 'E209', name: 'ERAFONE RUKO AHMAD YANI SERANG' },
  { code: 'E194', name: 'ERAFONE RUKO RANGKASBITUNG' },
  { code: 'E308', name: 'ERAFONE RUKO MAYOR SAFEI SERANG' },
  { code: 'E320', name: 'ERAFONE RUKO PANDEGLANG BANTEN' },
  { code: 'E589', name: 'ERAFONE RUKO PANIMBANG PANDEGLANG' },
  { code: 'E499', name: 'ERAFONE LABUAN PANDEGLANG' },
  { code: 'E544', name: 'ERAFONE RUKO MULTIBRAND CILEGON' },
  { code: 'E821', name: 'ERAFONE MB ANYER' },
  { code: 'E822', name: 'ERAFONE MB KRAGILAN' },
  { code: 'E833', name: 'ERAFONE RANGKASBITUNG 2' },
  { code: 'E879', name: 'ERAFONE MB CIPARE' },
  { code: 'E191', name: 'ERAFONE RUKO SURYA KENCANA PAMULANG' },
  { code: 'F022', name: 'ERAFONE 2.5 PAMULANG' },
  { code: 'E484', name: 'ERAFONE SERPONG PARADISE WALK' },
  { code: 'E087', name: 'ERAFONE ITC BSD' },
  { code: 'E941', name: 'ERAFONE MB RAYA SERPONG' },
  { code: 'E586', name: 'ERAFONE RUKO GRAHA RAYA' },
  { code: 'E834', name: 'ERAFONE KEDAUNG TANGSEL' },
  { code: 'E082', name: 'ERAFONE LIVING WORLD ALAM SUTERA' },
  { code: 'E088', name: 'ERAFONE AEON MAL BSD CITY' },
  { code: 'E119', name: 'ERAFONE TANGERANG CITY MALL' },
  { code: 'E696', name: 'ERAFONE MB RASUNA SAID' },
  { code: 'M176', name: 'ENM KISAMAUN' },
  { code: 'E422', name: 'ERAFONE RUKO M TOHA TANGERANG' },
  { code: 'E369', name: 'ERAFONE FRANCHISE RUKO BOROBUDUR RAYA' },
  { code: 'M061', name: 'MEGASTORE RUKO JATIUWUNG' },
  { code: 'E684', name: 'ERAFONE RUKO SANGIANG TANGERANG' },
  { code: 'E370', name: 'ERAFONE FRANCHISE RUKO BERINGIN KARAWACI' },
];
